#= Noether current for the covariant phase space framework.
#
# For a diffeomorphism generated by vector field xi, the Noether current is
# (Iyer & Wald 1994, Eq 2.10-2.12):
#
#   J^a = Theta^a(phi, Lie_xi phi) - xi^a L
#
# where Lie_xi phi is the Lie derivative of all dynamical fields along xi.
#
# Key identity (Iyer-Wald Eq 2.12):
#   J^a = E * Lie_xi phi + nabla_b Q^{ab}
# so J = dQ on-shell (when E = 0).
#
# For EH gravity with a Killing vector (Lie_xi g = 0), the Noether current
# simplifies to:
#   J^a = 2 G^{a b} xi_b + nabla_b(nabla^a xi^b - nabla^b xi^a)
# The first term vanishes on-shell, leaving J = dQ.
#
# Reference: Iyer & Wald (1994), PRD 50, 846, Eqs 2.10-2.12, 3.1-3.3.
=#

"""
    NoetherCurrent(expr, xi, lagrangian, potential)

Container for the Noether current J^a associated with a diffeomorphism
generated by vector field xi.

Fields:
- `expr::TensorExpr` -- J^a as a TensorExpr with one free upper index
- `xi::Symbol` -- the vector field generating the diffeomorphism
- `lagrangian::LagrangianDensity` -- the originating Lagrangian
- `potential::SymplecticPotential` -- the symplectic potential used
"""
struct NoetherCurrent
    expr::TensorExpr
    xi::Symbol
    lagrangian::LagrangianDensity
    potential::SymplecticPotential
end

"""
    noether_current(L::LagrangianDensity, field::Symbol, xi::Symbol;
                     registry::TensorRegistry=current_registry()) -> NoetherCurrent

Compute the Noether current J^a for a diffeomorphism generated by xi.

The Noether current is defined by (Iyer-Wald Eq 2.10):

    J^a = Theta^a(phi, Lie_xi phi) - xi^a L

Algorithm:
1. Compute the symplectic potential Theta^a(phi, delta_phi)
2. Substitute delta_phi -> Lie_xi(phi) to get Theta^a(phi, Lie_xi phi)
3. Compute xi^a * L (contraction of xi with the Lagrangian scalar)
4. Return J^a = Theta^a(Lie_xi phi) - xi^a L

# Examples

```julia
reg = TensorRegistry()
@manifold M4 dim=4 metric=g
define_curvature_tensors!(reg, :M4, :g)
define_covd!(reg, :D; manifold=:M4, metric=:g)
R = Tensor(:RicScalar, TIndex[])
L_EH = LagrangianDensity(R, [:g], :g, :D, 4)
register_tensor!(reg, TensorProperties(
    name=:xi, manifold=:M4, rank=(1, 0),
    symmetries=SymmetrySpec[], options=Dict{Symbol,Any}()))
J = noether_current(L_EH, :g, :xi; registry=reg)
```
"""
function noether_current(L::LagrangianDensity, field::Symbol, xi::Symbol;
                          registry::TensorRegistry=current_registry())
    with_registry(registry) do
        # Step 1: Compute the symplectic potential
        delta_field = Symbol(:delta_, field)
        sp = symplectic_potential(L, field; delta_field=delta_field, registry=registry)

        # Step 2: Substitute delta_phi -> Lie_xi(phi) in Theta
        # The Lie derivative of the metric is Lie_xi g_{ab} = nabla_a xi_b + nabla_b xi_a
        xi_vec = Tensor(xi, [up(:a)])  # temporary for Lie derivative computation
        theta_lie = _substitute_lie(sp.expr, delta_field, field, xi, L.covd, registry)

        # Step 3: xi^a * L -- the volume-form contraction term
        xi_L = Tensor(xi, [up(:a)]) * L.expr

        # Step 4: J^a = Theta^a(Lie_xi phi) - xi^a L
        J_expr = theta_lie - xi_L

        NoetherCurrent(J_expr, xi, L, sp)
    end
end

"""
    _substitute_lie(theta_expr, delta_field, field, xi, covd, reg) -> TensorExpr

Substitute the variation delta_phi in theta with the Lie derivative Lie_xi(phi).

For a metric field g_{ab}, the Lie derivative is:
    Lie_xi g_{ab} = nabla_a xi_b + nabla_b xi_a

This replaces every occurrence of `delta_field` in `theta_expr` with the
corresponding Lie derivative expression.
"""
function _substitute_lie(theta_expr::TensorExpr, delta_field::Symbol,
                          field::Symbol, xi::Symbol, covd::Symbol,
                          reg::TensorRegistry)
    # Walk the expression tree, replacing Tensor(:delta_field, indices)
    # with lie_derivative(xi, Tensor(:field, indices))
    _subst_lie_walk(theta_expr, delta_field, field, xi, covd)
end

function _subst_lie_walk(expr::Tensor, delta_field::Symbol,
                          field::Symbol, xi::Symbol, covd::Symbol)
    if expr.name == delta_field
        # Replace delta_field with Lie_xi(field)
        field_tensor = Tensor(field, expr.indices)
        xi_vec = Tensor(xi, [up(:__xi_lie)])
        lie_derivative(xi_vec, field_tensor)
    else
        expr
    end
end

function _subst_lie_walk(expr::TScalar, delta_field::Symbol,
                          field::Symbol, xi::Symbol, covd::Symbol)
    expr
end

function _subst_lie_walk(expr::TProduct, delta_field::Symbol,
                          field::Symbol, xi::Symbol, covd::Symbol)
    new_factors = TensorExpr[_subst_lie_walk(f, delta_field, field, xi, covd)
                             for f in expr.factors]
    tproduct(expr.scalar, new_factors)
end

function _subst_lie_walk(expr::TSum, delta_field::Symbol,
                          field::Symbol, xi::Symbol, covd::Symbol)
    tsum(TensorExpr[_subst_lie_walk(t, delta_field, field, xi, covd)
                    for t in expr.terms])
end

function _subst_lie_walk(expr::TDeriv, delta_field::Symbol,
                          field::Symbol, xi::Symbol, covd::Symbol)
    new_arg = _subst_lie_walk(expr.arg, delta_field, field, xi, covd)
    TDeriv(expr.index, new_arg, expr.covd)
end

"""
    noether_current_eh(metric::Symbol, xi::Symbol, covd::Symbol;
                        registry::TensorRegistry=current_registry()) -> TensorExpr

Return the explicit EH Noether current for a vector field xi.

For Einstein-Hilbert gravity, the Noether current is (Iyer-Wald Eq 3.1):

    J^a = 2 G^{a b} xi_b + nabla_b(nabla^a xi^b - nabla^b xi^a)

The first term vanishes on-shell (Einstein equations G_{ab} = 0),
and the second term is the divergence of the Noether potential Q^{ab}.

For a Killing vector (nabla_{(a} xi_{b)} = 0), the on-shell current
reduces to the pure divergence nabla_b(nabla^a xi^b - nabla^b xi^a)
= 2 nabla_b nabla^{[a} xi^{b]}.
"""
function noether_current_eh(metric::Symbol, xi::Symbol, covd::Symbol;
                             registry::TensorRegistry=current_registry())
    with_registry(registry) do
        used = Set{Symbol}([:a])
        b = fresh_index(used)

        # Term 1: 2 G^{a b} xi_b  (Einstein tensor contracted with xi)
        G_up = Tensor(:Ein, [up(:a), up(b)])
        xi_down = Tensor(xi, [down(b)])
        eom_term = (2 // 1) * G_up * xi_down

        # Term 2: nabla_b(nabla^a xi^b - nabla^b xi^a)
        # = nabla_b nabla^a xi^b - nabla_b nabla^b xi^a
        push!(used, b)
        c = fresh_index(used)

        # nabla^a xi^b
        grad_xi_1 = TDeriv(up(:a), Tensor(xi, [up(c)]), covd)
        # nabla^b xi^a -- but use dummy c for the nabla index
        grad_xi_2 = TDeriv(up(c), Tensor(xi, [up(:a)]), covd)

        # nabla_b(nabla^a xi^b - nabla^b xi^a) with b->c as dummy
        div_term = TDeriv(down(c), grad_xi_1 - grad_xi_2, covd)

        eom_term + div_term
    end
end

"""
    verify_noether_conservation(J::NoetherCurrent;
                                 registry::TensorRegistry=current_registry()) -> Bool

Verify that nabla_a J^a = 0 holds off-shell (as an identity following
from diffeomorphism invariance of the Lagrangian).

This constructs nabla_a J^a and simplifies. The divergence should vanish
identically for any diffeomorphism-covariant Lagrangian.

Returns `true` if the simplified divergence is zero.
"""
function verify_noether_conservation(J::NoetherCurrent;
                                      registry::TensorRegistry=current_registry())
    with_registry(registry) do
        covd = J.lagrangian.covd
        div_J = TDeriv(down(:a), J.expr, covd)
        result = simplify(div_J; registry=registry)
        result == ZERO
    end
end
