# conventions_probe_verify.jl — Phase 0 gate for TGR-bhs5 golden masters.
#
# Builds the same three sanity identities that conventions_probe.wl checks on
# the xAct side, and asserts TensorGR reduces each to zero. On success, writes
# `test/golden/conventions_probe_verified.txt` as the proof-of-gate artifact.
#
# Run:  julia --project test/golden/conventions_probe_verify.jl
#
# Physics is ground truth. If any identity fails to reduce, STOP and open a
# P0 bug on the divergent module per HANDOFF rule 6.

using TensorGR
using Printf

const VERIFY_PATH = joinpath(@__DIR__, "conventions_probe_verified.txt")

reg = TensorRegistry()

with_registry(reg) do
    @manifold M4 dim=4 metric=g
    define_curvature_tensors!(reg, :M4, :g)
    @covd D on=M4 metric=g

    results = Tuple{String,String,Bool,Any}[]

    # --- case 1: metric compatibility ---
    ac = down(:a); bc = down(:b); cc = down(:c)
    expr1 = TDeriv(cc, Tensor(:g, [ac, bc]), :D)
    red1 = simplify(expr1)
    push!(results, ("metric_compatibility",
                    "D_c g_{ab}",
                    red1 == TScalar(0),
                    red1))

    # --- case 2: Ricci contraction R^c_{acb} - R_{ab} ---
    # TensorGR convention (src/gr/curvature.jl:81): Ric_{ac} = Riem^b_{abc}.
    # Slots: up(:c) at position 1, down(:a) at 2, down(:c) at 3, down(:b) at 4.
    # Expr: Riem[c^, a_, c_, b_] - Ric[a_, b_]
    af = down(:a); bf = down(:b); cup = up(:c); cdn = down(:c)
    riem_contracted = Tensor(:Riem, [cup, af, cdn, bf])
    ric_direct = Tensor(:Ric, [af, bf])
    expr2 = riem_contracted - ric_direct
    red2 = simplify(expr2)
    push!(results, ("ricci_contraction",
                    "Riem^c_{a c b} - Ric_{a b}",
                    red2 == TScalar(0),
                    red2))

    # --- case 3: Ricci scalar trace g^{ab} R_{ab} - R ---
    ax = down(:a); bx = down(:b); aup = up(:a); bup = up(:b)
    expr3 = Tensor(:g, [aup, bup]) * Tensor(:Ric, [ax, bx]) -
            Tensor(:RicScalar, TIndex[])
    red3 = simplify(expr3)
    push!(results, ("ricci_scalar_trace",
                    "g^{ab} R_{ab} - R",
                    red3 == TScalar(0),
                    red3))

    # --- report ---
    println("="^60)
    println("TensorGR Phase-0 probe results")
    println("="^60)
    all_zero = true
    for (name, sym, ok, red) in results
        status = ok ? "PASS" : "FAIL"
        println(@sprintf("  [%s] %-24s  %s", status, name, sym))
        if !ok
            println("       reduced form: ", red)
            all_zero = false
        end
    end
    println("="^60)

    if all_zero
        open(VERIFY_PATH, "w") do io
            println(io, "# TGR-bhs5.3 GATE — conventions probe verification")
            println(io, "# Generated by test/golden/conventions_probe_verify.jl")
            println(io, "# Cross-check against test/golden/data/conventions_probe.json")
            println(io)
            for (name, sym, _, _) in results
                println(io, "$name  $sym  →  0  (PASS)")
            end
        end
        println("GATE PASSED. Wrote: $VERIFY_PATH")
    else
        println("GATE FAILED. Do NOT commit proof-of-gate. Investigate divergence.")
        exit(1)
    end
end
