#= Gauge transformations for perturbation theory.

Under an infinitesimal diffeomorphism generated by ξ^a:
  δ'₁ h_{ab} = δ₁ h_{ab} + £_ξ g_{ab}
  δ'₁ h_{ab} = h_{ab} + ∇_a ξ_b + ∇_b ξ_a    (for first order)

At higher orders, the Bruni-Damour recursion applies.
=#

"""
    gauge_transformation(pert_expr, ξ::Tensor, metric::Symbol, order::Int) -> TensorExpr

Apply a gauge transformation to a perturbation expression.
At order 1: δ' h_{ab} = h_{ab} + ∇_a ξ_b + ∇_b ξ_a
"""
function gauge_transformation(pert_expr::TensorExpr, ξ::Tensor, metric::Symbol;
                               order::Int=1)
    order != 1 && error("Only first-order gauge transformation implemented")

    # At first order, the gauge change is the Lie derivative of the background metric
    # £_ξ g_{ab} = ∇_a ξ_b + ∇_b ξ_a  (for Levi-Civita connection on flat background)
    # Using partial derivatives: ∂_a ξ_b + ∂_b ξ_a
    pert_expr + lie_derivative(ξ, Tensor(metric, free_indices(pert_expr) |>
        idxs -> length(idxs) >= 2 ? [idxs[1], idxs[2]] : TIndex[]))
end
