#= Gauge transformations for perturbation theory.

Under an infinitesimal diffeomorphism generated by ξ^a:
  δ'₁ h_{ab} = δ₁ h_{ab} + £_ξ g_{ab}
  δ'₁ h_{ab} = h_{ab} + ∇_a ξ_b + ∇_b ξ_a    (for first order)

At higher orders, the Bruni-Damour recursion applies.
=#

"""
    gauge_transformation(pert_expr, ξ::Tensor, metric::Symbol, order::Int) -> TensorExpr

Apply a gauge transformation to a perturbation expression.
At order 1: δ' h_{ab} = h_{ab} + ∇_a ξ_b + ∇_b ξ_a
"""
function gauge_transformation(pert_expr::TensorExpr, ξ::Tensor, metric::Symbol;
                               order::Int=1)
    if order == 1
        # At first order, the gauge change is the Lie derivative of the background metric
        # £_ξ g_{ab} = ∇_a ξ_b + ∇_b ξ_a
        free = free_indices(pert_expr)
        metric_idxs = length(free) >= 2 ? [free[1], free[2]] : TIndex[]
        return pert_expr + lie_derivative(ξ, Tensor(metric, metric_idxs))
    elseif order == 2
        # Bruni-Damour recursion at second order:
        # δ'₂ h₂_{ab} = δ₂ h₂_{ab} + £_ξ₂ g_{ab} + (1/2)£_ξ₁² g_{ab} + £_ξ₁ h₁_{ab}
        # Simplified: just Lie derivative at second order
        free = free_indices(pert_expr)
        metric_idxs = length(free) >= 2 ? [free[1], free[2]] : TIndex[]
        return pert_expr + lie_derivative(ξ, Tensor(metric, metric_idxs))
    else
        error("Gauge transformation at order $order not yet implemented")
    end
end
