using Libdl

# Path to the compiled shared library
const _libxperm_path = joinpath(@__DIR__, "..", "..", "deps", "libxperm." * Libdl.dlext)
const _libxperm = Ref{Ptr{Cvoid}}(C_NULL)

const _lib_lock = ReentrantLock()
function _ensure_lib_loaded()
    _libxperm[] != C_NULL && return _libxperm[]
    lock(_lib_lock) do
        _libxperm[] == C_NULL && (_libxperm[] = Libdl.dlopen(_libxperm_path))
    end
    _libxperm[]
end

"""
    xperm_schreier_sims(base_hint, generators, n) -> (newbase, sgs)

Compute a Strong Generating Set using the Schreier-Sims algorithm.

# Arguments
- `base_hint::Vector{Int32}`: initial base points (1-indexed)
- `generators::Vector{Perm}`: generating permutations (degree `n`)
- `n::Int`: degree of the permutation group

# Returns
- `newbase::Vector{Int32}`: computed base
- `sgs::Vector{Perm}`: strong generating set
"""
function xperm_schreier_sims(base_hint::Vector{Int32}, generators::Vector{Perm}, n::Int)
    _ensure_lib_loaded()

    bl = length(base_hint)
    m = length(generators)

    # Flatten generators into a contiguous Int32 array (m permutations of length n)
    GS = Vector{Int32}(undef, m * n)
    for (i, g) in enumerate(generators)
        @assert degree(g) == n "Generator degree $(degree(g)) != n=$n"
        copyto!(GS, (i-1)*n + 1, g.data, 1, n)
    end

    # Output buffers
    newbase = Vector{Int32}(undef, n)  # at most n base points
    nbl = Ref{Cint}(0)
    nm = Ref{Cint}(0)
    num = Ref{Cint}(0)

    # newGS must be C-allocated because schreier_sims_step may realloc it.
    # Allocate initial space for m*n elements, matching the C code's expectation.
    newGS_ptr = Libc.malloc(m * n * sizeof(Cint))
    newGS_ref = Ref{Ptr{Cint}}(Ptr{Cint}(newGS_ptr))

    ccall(
        (:schreier_sims, _libxperm_path),
        Cvoid,
        (Ptr{Cint}, Cint, Ptr{Cint}, Cint, Cint,
         Ptr{Cint}, Ptr{Cint}, Ptr{Ptr{Cint}}, Ptr{Cint}, Ptr{Cint}),
        base_hint, bl, GS, m, n,
        newbase, nbl, newGS_ref, nm, num
    )

    # Extract results
    result_bl = Int(nbl[])
    result_m = Int(nm[])
    result_base = newbase[1:result_bl]

    # Copy SGS from C-allocated memory into Julia arrays
    result_sgs = Vector{Perm}(undef, result_m)
    gs_ptr = newGS_ref[]
    for i in 1:result_m
        pdata = Vector{Int32}(undef, n)
        for j in 1:n
            pdata[j] = unsafe_load(gs_ptr, (i-1)*n + j)
        end
        result_sgs[i] = Perm(pdata)
    end

    # Free C-allocated memory
    Libc.free(newGS_ref[])

    return result_base, result_sgs
end

"""
    xperm_canonical_perm(perm, base, generators, free_slots, dummy_pairs, n) -> Perm

Find the canonical representative of `perm` under the slot symmetry group
generated by `generators`, with free and dummy index information.

Uses the simpler `canonical_perm` interface (not `canonical_perm_ext`).

# Arguments
- `perm::Perm`: permutation to canonicalize (degree `n`)
- `base::Vector{Int32}`: base for the symmetry group
- `generators::Vector{Perm}`: symmetry group generators
- `free_slots::Vector{Int32}`: positions of free index slots (1-indexed)
- `dummy_pairs::Vector{Int32}`: paired dummy slot positions [u1,d1, u2,d2, ...]
- `n::Int`: degree

# Returns
- Canonical permutation. Sign info is encoded in the last two points:
  `result[n-1]==n-1, result[n]==n` means positive sign;
  `result[n-1]==n, result[n]==n-1` means negative sign;
  `result == zeros` means the expression is zero.
"""
function xperm_canonical_perm(perm::Perm, base::Vector{Int32},
                              generators::Vector{Perm},
                              free_slots::Vector{Int32},
                              dummy_pairs::Vector{Int32},
                              n::Int)
    _ensure_lib_loaded()
    @assert degree(perm) == n

    bl = length(base)
    m = length(generators)
    fl = length(free_slots)
    # dummy_pairs has format [u1,d1, u2,d2,...] so dpl = number of pairs
    dpl = div(length(dummy_pairs), 2)

    # Flatten generators
    GS = Vector{Int32}(undef, max(m * n, 1))
    for (i, g) in enumerate(generators)
        @assert degree(g) == n
        copyto!(GS, (i-1)*n + 1, g.data, 1, n)
    end

    # SGSQ=0 means we supply a GS (not necessarily strong), and xperm will
    # compute the SGS internally.
    SGSQ = Cint(0)

    # ob=1 means order base points (standard)
    ob = Cint(1)

    # metricQ: 1 for symmetric metric, -1 for antisymmetric, 0 for no metric
    # For now, default to symmetric metric for dummy pairs
    metricQ = Cint(dpl > 0 ? 1 : 0)

    # Output buffer
    cperm = Vector{Int32}(undef, n)

    ccall(
        (:canonical_perm, _libxperm_path),
        Cvoid,
        (Ptr{Cint},
         Cint, Ptr{Cint}, Cint, Ptr{Cint}, Cint, Cint,
         Ptr{Cint}, Cint, Ptr{Cint}, Cint, Cint, Cint,
         Ptr{Cint}),
        perm.data,
        SGSQ, base, bl, GS, m, n,
        free_slots, fl, dummy_pairs, dpl, ob, metricQ,
        cperm
    )

    Perm(cperm)
end
